# required vars:
# - uid
# - entity_id

sensor:
  - id: ${uid}_battery_soc
    platform: homeassistant
    entity_id: ${entity_id}
    on_value:
      - lvgl.label.update:
          id: ${uid}_label
          text: !lambda |-
            return ("Battery SoC: " + std::to_string((int)x) + "%").c_str();
